name: get pull request info for Dingding

on:
  push:
    branches:
      - master

jobs:
  spring-boot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    # 此处省略具体的业务代码    
   
    # 获取PR信息并将其添加到环境变量
    - name: set PR_INFO 
      run: |
        echo PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') >> $GITHUB_ENV
        echo PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
        echo PR_URL=$(jq --raw-output .pull_request.html_url "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
        echo PR_USER=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
    
    # 打印环境变量
    - name: print env
      run: printenv
    # 打印事件变量 event
    - name: print event
      run: more /home/runner/work/_temp/_github_workflow/event.json

    - name: WeChat Work notification by text
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f93956cb-6016-40c1-8640-c9c10adc9fed
      with:
        msgtype: ${{ env }}
        content: 广州今日天气：29度，大部分多云，降雨概率：60%
        mentioned_list: '["wangqing","@all"]'
        mentioned_mobile_list: '["13800001111","@all"]'
     
    # # 发送钉钉消息
    # - name: build success
    #   if: ${{ success() }}
    #   uses: fifsky/dingtalk-action@master
    #   with:
    #     url: https://oapi.dingtalk.com/robot/send?access_token=这里写钉钉机器人的token
    #     type: markdown
    #     content: |
    #       # 💯👨‍💻 Success 🎉🎉🎉
    #       > Maven Build of [# ${{ env.PR_TITLE }}](${{ env.PR_URL }}) by ${{ env.PR_USER }} success
    #       > ^_^ from github action message 
    # - name: maven build failure
    #   if: ${{ failure() }}
    #   uses: fifsky/dingtalk-action@master
    #   with:
    #     url: https://oapi.dingtalk.com/robot/send?access_token=${{ env.DING_TOKEN}}如果是公有项目则应该在github项目中依次点击settings -> secret 添加一个DING_TOKEN，并设置为自己的钉钉机器人token
    #     type: markdown
    #     content: |
    #       # 💤🤷‍♀️ failure 🙅‍♂️💣
    #       > Maven Build of [# ${{ env.PR_TITLE }}](${{ env.PR_URL }}) by ${{ env.PR_USER }} failure
    #       > (⋟﹏⋞)   from github action message
