name: Merge pre-master

on:
  # 推送代码后触发
  push:
    branches:
      - master
  # 定时任务触发，使用 cron 规则，这里默认一小时执行一次
#   schedule:
#     - cron: '0 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: read-all|write-all
    steps:
      - uses: actions/checkout@v2
        with:
          user_name: ${{ secrets.USER_NAME }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge origin pre-master
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "content-type: application/json" \
          -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/wanghuajin-bello/vue-study/merges \
          -d '{"base":"pre-master","head":"master"}'
